### ISSUE TITLE
Removes elements from the DOM

### ISSUE THREAD

**Issue by bravokiloecho** [bigspaceship/shine.js#9]
A really beautiful plugin this...

But I'm having a little trouble when applying it to a container which has (so far) 12 children to whom I want shadows to be applied. However, when called, the plugin remove 6 of these children. I couldn't find any mention of this kind of behaviour in the documentation, or an option for specifying the max number of child elements.

So I was wondering... Is this intended behaviour?

I can understand there would be performance issues if there are too many elements, but it might be useful to know that's what's happening. Or even to be able to set the max number of elements.

(I did look through the plugin's JS but couldn't spot where this might be happening. I'd be happy to try and implement an a maxElements option...)

Thanks!

**Comment by benjaminbojko** [comment]
Shine does modify the contents of the container to add shadow elements, but there shouldn't be a limit on the maximum number of items. It's hard to say what exactly is happening without looking at your code. Do you have an example that you could share?

**Comment by bravokiloecho** [comment]
Hi Benjamin,

Thanks so much for getting back to me. I tried several things to try and find the route of this problem but to no avail. I even rebuilt most of the site in codepen where eveything actually worked as intended!

_However_ I did some digging around the in the plugin and I found the source of the issue...

The problem stemmed from the `splitChildren` prototype. What was happening was that during the `for` loop over the childNodes NodeList object was being emptied of the child that was being appended to the `wrapperElement` when it was being passed into the `appendChild` method. This was also effecting the number of iterations of the `foor` loop; there were 12 children on my site, and only 6 loops were being called.) (I have no idea why this was happening on my site, but not on the codepen version. I tried it in Chrome, Safari, and Firefox and all had the same issue.)

A fix that worked for me had two steps:
1. Cache the `childNodes.length` as a variable and use this value in the `for` loop.
2. Define the `child` always as `childNodes[0]` (rather than `childNodes[i]`.
I've applied these changes in this commit: SHA: 73f7c995e9b7d6927264ce7aa2d224745601e1a8

It's quite possible that if the original method works for people, then my new method won't so I'm not sure it's worth making a pull request.

I had thought of another solution that would be more robust but slightly less efficient. This would involve...
1. Converting the childNodes object into an array (as documented [here](https://developer.mozilla.org/en/docs/Web/API/NodeList)).
2. Reversing the array.
3. Then within the `for` loop, defining the `child` as:
``` 
var currentChildIndex = childNodesLength - i - 1;
var child = childNodes[ currentChildIndex ];
```

I hope this all makes sense and I'd be curious to get your thoughts.

**Comment by benjaminbojko** [comment]
That's actually a great find and I'm strongly considering merging this into the main repo. From the looks of it, your additions should make the script behave as intended. I assume that this hasn't been a larger issue since the library is mostly used decoratively in fairly straight forward settings. Let me take a closer look and I'll probably merge then.
